export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const LOADING_ACCOUNTS = 'LOADING_TODOS';

export const ACCOUNT_AUTHENTICATED = 'ACCOUNT_AUTHENTICATED';